import { ScrollView, styled } from 'tamagui'

import { AppProviders } from '../providers'
import { Button } from '../components/primitives/Button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/data-display/Card'
import { Badge } from '../components/feedback/Badge'
import { Separator } from '../components/data-display/Separator'
import { componentCatalog } from './components-map'
import { FlowDemos } from './FlowDemos'

const GalleryContainer = styled(ScrollView, {
  name: 'GalleryContainer',
  padding: '$6',
  gap: '$4',
})

const GalleryCard = styled(Card, {
  borderColor: '$borderColor',
  padding: '$4',
  variants: {
    status: {
      implemented: {
        borderColor: '$success',
      },
      placeholder: {
        borderColor: '$warning',
      },
      missing: {
        borderColor: '$destructive',
      },
    },
  },
})

const StatusBadge = styled(Badge, {
  marginLeft: '$3',
})

export const TamaguiGallery = () => {
  const implemented = componentCatalog.filter((c) => c.status === 'implemented')
  const placeholders = componentCatalog.filter((c) => c.status === 'placeholder')

  return (
    <AppProviders>
      <GalleryContainer>
        <Card>
          <CardHeader>
            <CardTitle>Tamagui Migration Gallery</CardTitle>
            <CardDescription>
              Reference showcase for shadcn components ported to Tamagui. Use this page when verifying parity
              or identifying placeholder/missing implementations.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button size="sm" variant="outline">
              Total Components: {componentCatalog.length}
            </Button>
          </CardContent>
        </Card>

        {implemented.map((component) => (
          <GalleryCard key={component.name} status="implemented">
            <CardHeader>
              <CardTitle>
                {component.name}
                <StatusBadge variant="success">Implemented</StatusBadge>
              </CardTitle>
              <CardDescription>{component.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <Separator orientation="horizontal" />
              <CardDescription>Import: {component.importPath}</CardDescription>
            </CardContent>
          </GalleryCard>
        ))}

        {placeholders.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Placeholder Implementations</CardTitle>
              <CardDescription>Components generated by agents that need full Tamagui parity work.</CardDescription>
            </CardHeader>
            <CardContent>
              {placeholders.map((component) => (
                <GalleryCard key={component.name} status="placeholder">
                  <CardHeader>
                    <CardTitle>
                      {component.name}
                      <StatusBadge variant="warning">Placeholder</StatusBadge>
                    </CardTitle>
                    <CardDescription>{component.description}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <CardDescription>Import: {component.importPath}</CardDescription>
                  </CardContent>
                </GalleryCard>
              ))}
            </CardContent>
          </Card>
        )}
        {/* <FlowDemos /> */}
      </GalleryContainer>
    </AppProviders>
  )
}
