#!/bin/bash

# Jules Swarm Launch Script - Batch 3 & 4
# Generated by Antigravity
# Updated to pass full prompt as single line argument

echo "🚀 Launching Jules Swarm for Batches 3 & 4..."

# Common Context
ROLE="You are a Senior Engineer acting as an autonomous extension of my team."
CONTEXT="1. **Implicit Context**: Read **all** files in \`docs/\` to understand the project state.\n2. **Constitution**: Strictly follow \`AGENTS.md\` for coding standards, stack rules, and file organization.\n3. **Trust**: I assume the codebase is self-explanatory. If you see a pattern (e.g., how tests are written), follow it.\n4. **Task Title**: Start the prompt with repo name + the simplest possible task title."
PROTOCOL="1. **Analyze**: Compare the task against the current codebase state.\n2. **Implement**: Write the code, ensuring it matches the project's existing patterns.\n3. **Verify**: Run existing tests or write new ones to confirm the task is complete."

# Session 1: Autocomplete Spec
echo "Starting Session 1: Autocomplete Spec..."
TASK_1="- [ ] **Task 35e**: Create specs for \`Autocomplete\`"
PROMPT_1="ivisa-tamagui - Autocomplete Spec\n\n# Role\n$ROLE\n\n# Context & Rules\n$CONTEXT\n\n# The Task\nExecute the following task(s) exactly as defined in our task list:\n\n\"\"\"\n$TASK_1\n\"\"\"\n\n# Execution Protocol\n$PROTOCOL"
jules remote new --repo ivisa-tamagui --session "$PROMPT_1"

# Session 2: Form Atoms
echo "Starting Session 2: Form Atoms..."
TASK_2="- [ ] **Task 36c**: Implement \`field\` component\n- [ ] **Task 36d**: Implement \`input-group\`\n- [ ] **Task 36h**: Implement \`native-select\`"
PROMPT_2="ivisa-tamagui - Form Atoms\n\n# Role\n$ROLE\n\n# Context & Rules\n$CONTEXT\n\n# The Task\nExecute the following task(s) exactly as defined in our task list:\n\n\"\"\"\n$TASK_2\n\"\"\"\n\n# Execution Protocol\n$PROTOCOL"
jules remote new --repo ivisa-tamagui --session "$PROMPT_2"

# Session 3: Layout Atoms
echo "Starting Session 3: Layout Atoms..."
TASK_3="- [ ] **Task 36a**: Implement \`button-group\`\n- [ ] **Task 36b**: Implement \`empty\` state component\n- [ ] **Task 36e**: Implement \`item\` component"
PROMPT_3="ivisa-tamagui - Layout Atoms\n\n# Role\n$ROLE\n\n# Context & Rules\n$CONTEXT\n\n# The Task\nExecute the following task(s) exactly as defined in our task list:\n\n\"\"\"\n$TASK_3\n\"\"\"\n\n# Execution Protocol\n$PROTOCOL"
jules remote new --repo ivisa-tamagui --session "$PROMPT_3"

# Session 4: UI Elements
echo "Starting Session 4: UI Elements..."
TASK_4="- [ ] **Task 36i**: Implement \`sonner\` (Toast alternative)\n- [ ] **Task 36j**: Implement \`table\` (Basic table)"
PROMPT_4="ivisa-tamagui - UI Elements\n\n# Role\n$ROLE\n\n# Context & Rules\n$CONTEXT\n\n# The Task\nExecute the following task(s) exactly as defined in our task list:\n\n\"\"\"\n$TASK_4\n\"\"\"\n\n# Execution Protocol\n$PROTOCOL"
jules remote new --repo ivisa-tamagui --session "$PROMPT_4"

echo "✅ All sessions launched! Check your Jules dashboard."
